repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v14.0.1'  # Use the sha / tag you want to point at
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.6.0'  # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
